version: '3'
services:
    nodejs:
        depends_on:
            - mongo
        build: .
        networks: 
            - front
            - db

    mongo:
        image: mongo:latest
        volumes:
            - mongodb_data_container:/data/db
        networks: 
            - db
    
volumes:
    mongodb_data_container:


networks:
    front:
        external:
            name: nginx
    db: