version: '3'
services:
    nodejs:
        depends_on:
            - mongo
        container_name: fit_node
        build: .
        volumes:
             - ./dist/images/boards:/app/dist/images/boards
        networks: 
            - front
            - db

    mongo:
        image: mongo:latest
        container_name: fit_mongo
        volumes:
            - mongodb_data_container:/data/db
        networks: 
            - db
    
volumes:
    mongodb_data_container:


networks:
    front:
        external:
            name: nginx
    db: